-- Sprint 18 — Backfill region (généré depuis src/lib/city-regions.json — ne pas éditer à la main)
WITH map(ville, region) AS (VALUES
('Toulon','Provence-Alpes-Côte d''Azur'),
('Marseille','Provence-Alpes-Côte d''Azur'),
('Nice','Provence-Alpes-Côte d''Azur'),
('Avignon','Provence-Alpes-Côte d''Azur'),
('Cannes','Provence-Alpes-Côte d''Azur'),
('Aix-en-Provence','Provence-Alpes-Côte d''Azur'),
('Antibes','Provence-Alpes-Côte d''Azur'),
('Saint-Tropez','Provence-Alpes-Côte d''Azur'),
('Embrun','Provence-Alpes-Côte d''Azur'),
('Arles','Provence-Alpes-Côte d''Azur'),
('Pertuis','Provence-Alpes-Côte d''Azur'),
('Lyon','Auvergne-Rhône-Alpes'),
('Clermont-Ferrand','Auvergne-Rhône-Alpes'),
('Grenoble','Auvergne-Rhône-Alpes'),
('Saint-Etienne','Auvergne-Rhône-Alpes'),
('Chambery','Auvergne-Rhône-Alpes'),
('Annecy','Auvergne-Rhône-Alpes'),
('Valence','Auvergne-Rhône-Alpes'),
('Aime-la-Plagne','Auvergne-Rhône-Alpes'),
('Combloux','Auvergne-Rhône-Alpes'),
('Sallanches','Auvergne-Rhône-Alpes'),
('Passy','Auvergne-Rhône-Alpes'),
('Ugine','Auvergne-Rhône-Alpes'),
('La Mure','Auvergne-Rhône-Alpes'),
('Gannat','Auvergne-Rhône-Alpes'),
('Orcet','Auvergne-Rhône-Alpes'),
('Polminhac','Auvergne-Rhône-Alpes'),
('Langeac','Auvergne-Rhône-Alpes'),
('Livron-sur-Drôme','Auvergne-Rhône-Alpes'),
('Menglon','Auvergne-Rhône-Alpes'),
('Nyons','Auvergne-Rhône-Alpes'),
('Vesc','Auvergne-Rhône-Alpes'),
('Clérieux','Auvergne-Rhône-Alpes'),
('Couzon','Auvergne-Rhône-Alpes'),
('La Grand-Croix','Auvergne-Rhône-Alpes'),
('Pleaux','Auvergne-Rhône-Alpes'),
('Arpajon-sur-Cère','Auvergne-Rhône-Alpes'),
('Saint-Santin-Cantalès','Auvergne-Rhône-Alpes'),
('Saint-Bonnet-de-Rochefort','Auvergne-Rhône-Alpes'),
('Brest','Bretagne'),
('Lorient','Bretagne'),
('Saint-Brieuc','Bretagne'),
('Quimper','Bretagne'),
('Vannes','Bretagne'),
('Rennes','Bretagne'),
('Bruz','Bretagne'),
('Retiers','Bretagne'),
('Lalleu','Bretagne'),
('Availles-sur-Seiche','Bretagne'),
('Lamballe','Bretagne'),
('Langueux','Bretagne'),
('La Méaugon','Bretagne'),
('Minihy-Tréguier','Bretagne'),
('Ploufragan','Bretagne'),
('Ploumagoar','Bretagne'),
('Gouarec','Bretagne'),
('Erquy','Bretagne'),
('Lesneven','Bretagne'),
('Sizun','Bretagne'),
('Pluguffan','Bretagne'),
('Plonéour-Lanvern','Bretagne'),
('Pouldreuzic','Bretagne'),
('Esquibien','Bretagne'),
('CAMARET SUR MER','Bretagne'),
('Telgruc-sur-Mer','Bretagne'),
('Riec-sur-Bélon','Bretagne'),
('Port-Louis','Bretagne'),
('Bordeaux','Nouvelle-Aquitaine'),
('Pau','Nouvelle-Aquitaine'),
('Limoges','Nouvelle-Aquitaine'),
('La Rochelle','Nouvelle-Aquitaine'),
('Begles','Nouvelle-Aquitaine'),
('Talence','Nouvelle-Aquitaine'),
('Villenave d''Ornon','Nouvelle-Aquitaine'),
('Gradignan','Nouvelle-Aquitaine'),
('Merignac','Nouvelle-Aquitaine'),
('Cenon','Nouvelle-Aquitaine'),
('Eysines','Nouvelle-Aquitaine'),
('Lormont','Nouvelle-Aquitaine'),
('Saint Medard en Jalles','Nouvelle-Aquitaine'),
('Ambès','Nouvelle-Aquitaine'),
('Le Bouscat','Nouvelle-Aquitaine'),
('Ambarès et Lagrave','Nouvelle-Aquitaine'),
('Blanquefort','Nouvelle-Aquitaine'),
('Bouliac','Nouvelle-Aquitaine'),
('Carbon Blanc','Nouvelle-Aquitaine'),
('Artigues près Bordeaux','Nouvelle-Aquitaine'),
('Martignas sur Jalle','Nouvelle-Aquitaine'),
('Saint Louis de Montferrand','Nouvelle-Aquitaine'),
('Bruges','Nouvelle-Aquitaine'),
('Floirac','Nouvelle-Aquitaine'),
('Le Haillan','Nouvelle-Aquitaine'),
('Pessac','Nouvelle-Aquitaine'),
('Bassens','Nouvelle-Aquitaine'),
('Bayonne','Nouvelle-Aquitaine'),
('Biarritz','Nouvelle-Aquitaine'),
('Cestas','Nouvelle-Aquitaine'),
('Parempuyre','Nouvelle-Aquitaine'),
('Saint-Jean-de-Luz','Nouvelle-Aquitaine'),
('Canéjan','Nouvelle-Aquitaine'),
('Arcachon','Nouvelle-Aquitaine'),
('Hendaye','Nouvelle-Aquitaine'),
('Oloron-Sainte-Marie','Nouvelle-Aquitaine'),
('Le Taillan Medoc','Nouvelle-Aquitaine'),
('Poitiers','Nouvelle-Aquitaine'),
('Niort','Nouvelle-Aquitaine'),
('Montmorillon','Nouvelle-Aquitaine'),
('Châtellerault','Nouvelle-Aquitaine'),
('Valdivienne','Nouvelle-Aquitaine'),
('La Grimaudière','Nouvelle-Aquitaine'),
('Thouars','Nouvelle-Aquitaine'),
('Saint-Jean-de-Thouars','Nouvelle-Aquitaine'),
('Coulonges-Thouarsais','Nouvelle-Aquitaine'),
('Le Busseau','Nouvelle-Aquitaine'),
('Mouhet','Nouvelle-Aquitaine'),
('Neuvic-Entier','Nouvelle-Aquitaine'),
('Droux','Nouvelle-Aquitaine'),
('Aubusson','Nouvelle-Aquitaine'),
('Anzême','Nouvelle-Aquitaine'),
('La Chaussade','Nouvelle-Aquitaine'),
('Lavaveix-les-Mines','Nouvelle-Aquitaine'),
('Ussel','Nouvelle-Aquitaine'),
('Corrèze','Nouvelle-Aquitaine'),
('Perpignan','Occitanie'),
('Montpellier','Occitanie'),
('Toulouse','Occitanie'),
('Beziers','Occitanie'),
('Narbonne','Occitanie'),
('Foix','Occitanie'),
('Mirepoix','Occitanie'),
('Verniolle','Occitanie'),
('Saint-Jean-de-Verges','Occitanie'),
('Ax-les-Thermes','Occitanie'),
('Argelès-sur-Mer','Occitanie'),
('Saint-Cyprien','Occitanie'),
('Alénya','Occitanie'),
('Estavar','Occitanie'),
('Latour-Bas-Elne','Occitanie'),
('Espalion','Occitanie'),
('Laguiole','Occitanie'),
('Le Monastère','Occitanie'),
('Salles-la-Source','Occitanie'),
('Roquecourbe','Occitanie'),
('Sémalens','Occitanie'),
('Gajan','Occitanie'),
('Castéra-Lectourois','Occitanie'),
('Bivès','Occitanie'),
('Strasbourg','Grand Est'),
('Reims','Grand Est'),
('Metz','Grand Est'),
('Nancy','Grand Est'),
('Mulhouse','Grand Est'),
('Troyes','Grand Est'),
('Charleville-Mézières','Grand Est'),
('Sedan','Grand Est'),
('Marby','Grand Est'),
('Sainte-Savine','Grand Est'),
('Brillecourt','Grand Est'),
('Aix-Villemaur-Pâlis','Grand Est'),
('Golbey','Grand Est'),
('Thaon-les-Vosges','Grand Est'),
('Rugney','Grand Est'),
('Bois-de-Haye','Grand Est'),
('Deneuvre','Grand Est'),
('Pournoy-la-Grasse','Grand Est'),
('Lille','Hauts-de-France'),
('Amiens','Hauts-de-France'),
('Beuvry','Hauts-de-France'),
('Creil','Hauts-de-France'),
('Mogneville','Hauts-de-France'),
('Verneuil-en-Halatte','Hauts-de-France'),
('Paris','Île-de-France'),
('Arcueil','Île-de-France'),
('Saint-Ouen','Île-de-France'),
('Rouen','Normandie'),
('Caen','Normandie'),
('Saint-Germain-du-Corbéis','Normandie'),
('Valframbert','Normandie'),
('Héloup','Normandie'),
('Pointel','Normandie'),
('Saint-Nazaire','Pays de la Loire'),
('Angers','Pays de la Loire'),
('Le Mans','Pays de la Loire'),
('Nantes','Pays de la Loire'),
('Châteaubriant','Pays de la Loire'),
('Sougé-le-Ganelon','Pays de la Loire'),
('Auchay-sur-Vendée','Pays de la Loire'),
('Saint-Martin-de-Fraigneau','Pays de la Loire'),
('Saint-Maurice-le-Girard','Pays de la Loire'),
('Tours','Centre-Val de Loire'),
('Orleans','Centre-Val de Loire'),
('Orléans','Centre-Val de Loire'),
('Bourges','Centre-Val de Loire'),
('Gien','Centre-Val de Loire'),
('Briare','Centre-Val de Loire'),
('Châtillon-sur-Loire','Centre-Val de Loire'),
('Saint-Firmin-sur-Loire','Centre-Val de Loire'),
('Vienne-en-Val','Centre-Val de Loire'),
('Villorceau','Centre-Val de Loire'),
('Suèvres','Centre-Val de Loire'),
('Valloire-sur-Cisse','Centre-Val de Loire'),
('Marchenoir','Centre-Val de Loire'),
('La Chapelle-du-Noyer','Centre-Val de Loire'),
('La Chapelle-sur-Aveyron','Centre-Val de Loire'),
('Châteauneuf-sur-Cher','Centre-Val de Loire'),
('Dun-sur-Auron','Centre-Val de Loire'),
('Saint-Doulchard','Centre-Val de Loire'),
('Vouvray','Centre-Val de Loire'),
('Saint-Avertin','Centre-Val de Loire'),
('Nouâtre','Centre-Val de Loire'),
('Montoire-sur-le-Loir','Centre-Val de Loire'),
('La Berthenoux','Centre-Val de Loire'),
('Neuvy-Pailloux','Centre-Val de Loire'),
('Ceaulmont','Centre-Val de Loire'),
('Dijon','Bourgogne-Franche-Comté'),
('Besancon','Bourgogne-Franche-Comté'),
('Morteau','Bourgogne-Franche-Comté'),
('Valdahon','Bourgogne-Franche-Comté'),
('Fontain','Bourgogne-Franche-Comté'),
('Touillon-et-Loutelet','Bourgogne-Franche-Comté'),
('Marcilly-Ogny','Bourgogne-Franche-Comté'),
('Sussey','Bourgogne-Franche-Comté'),
('Neuvy-sur-Loire','Bourgogne-Franche-Comté'),
('Esch-sur-Alzette','Luxembourg'),
('Petange','Luxembourg'),
('Differdange','Luxembourg'),
('Mersch','Luxembourg'),
('Dudelange','Luxembourg'),
('Strassen','Luxembourg'),
('Hesperange','Luxembourg'),
('Bertrange','Luxembourg'),
('Grevenmacher','Luxembourg'),
('Schifflange','Luxembourg'),
('Wiltz','Luxembourg'),
('Ettelbruck','Luxembourg'),
('Luxembourg','Luxembourg'),
('Sanem','Luxembourg'),
('Echternach','Luxembourg'),
('Junglinster','Luxembourg'),
('Kayl','Luxembourg'),
('Remich','Luxembourg'),
('Rumelange','Luxembourg'),
('Bettembourg','Luxembourg'),
('Contern','Luxembourg'),
('Diekirch','Luxembourg'),
('Mamer','Luxembourg'),
('Sandweiler','Luxembourg'),
('Walferdange','Luxembourg'),
('Lorentzweiler','Luxembourg'),
('Mondercange','Luxembourg')
)
UPDATE leads l SET region = m.region
FROM map m
WHERE l.source='cold_call' AND l.region IS NULL
  AND ( btrim(l.location) = m.ville
     OR substring(btrim(l.location) from '\d{4,5}\s+([^,]+)') = m.ville );
